-- Sammlung aller Datenbanktabellen

/**/
--
-- Tabellenstruktur für Tabelle Person
--

CREATE TABLE PERSON (
  ID int(11) NOT NULL,
  VORNAME varchar(50) NOT NULL,
  NACHNAME varchar(50) NOT NULL,
  GEBURTSTAG date NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle TRAINER
--

CREATE TABLE TRAINER (
  ID int(11) NOT NULL,
  PERSON_ID int(11) NOT NULL,
  LIZENZ varchar(50) NOT NULL,
  ERFAHRUNG int(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle FUSSBALLSPIELER
--

CREATE TABLE FUSSBALLSPIELER (
  ID int(11) NOT NULL,
  PERSON_ID int(11) NOT NULL,
  TORE int(11) NOT NULL,
  POSITION varchar(50) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle HANDBALLSPIELER
--

CREATE TABLE HANDBALLSPIELER (
  ID int(11) NOT NULL,
  PERSON_ID int(11) NOT NULL,
  TORE int(11) NOT NULL,
  POSITION varchar(50) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle TENNISSPIELER
--

CREATE TABLE TENNISSPIELER (
  ID int(11) NOT NULL,
  PERSON_ID int(11) NOT NULL,
  ANZAHL_SPIELE int(11) NOT NULL,
  ANZAHL_GEWONNEN int(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle PHYSIO
--

CREATE TABLE PHYSIO (
  ID int(11) NOT NULL,
  PERSON_ID int(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle MANNSCHAFT
--

CREATE TABLE MANNSCHAFT (
  ID int(11) NOT NULL,
  NAME varchar(50) NOT NULL,
  STADT varchar(50) NOT NULL,
  GRUENDUNGSJAHR date NOT NULL,
  SPORTART_ID int(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle PERSONEN_MANNSCHAFTEN
--

CREATE TABLE PERSONEN_MANNSCHAFTEN (
  ID int(11) NOT NULL,
  PERSON_ID int(11) NOT NULL,
  MANNSCHAFT_ID int(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle SPORTART
--

CREATE TABLE SPORTART (
  ID int(11) NOT NULL,
  BEZEICHNUNG varchar(50) NOT NULL,
  ANZAHL_PUNKTE_SIEG int(11) NOT NULL,
  ANZAHL_PUNKTE_VERLUST int(11) NOT NULL,
  ANZAHL_PUNKTE_PATT int(11) NOT NULL,
  ANZAHL_SPIELER_PRO_TEAM int(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle TURNIERART
--
CREATE TABLE TURNIERART (
	ID INT(11) NOT NULL,
	BEZEICHNUNG VARCHAR(50) NOT NULL	
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle TURNIER
--
CREATE TABLE TURNIER (
	ID INT(11) NOT NULL,
	BEZEICHNUNG VARCHAR(50) NOT NULL,
	SPORTART_ID INT(11) NOT NULL,
	TURNIERART_ID INT(11) NOT NULL,
	ABGESCHLOSSEN TINYINT(1) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle TURNIER_PERSON
--
CREATE TABLE TURNIER_PERSON (
	ID INT(11) NOT NULL,
	TURNIER_ID INT(11) NOT NULL,
	PERSON_ID INT(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle TURNIER_MANNSCHAFT
--
CREATE TABLE TURNIER_MANNSCHAFT (
	ID INT(11) NOT NULL,
	TURNIER_ID INT(11) NOT NULL,
	MANNSCHAFT_ID INT(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle MANNSCHAFTSSPIEL
--
CREATE TABLE MANNSCHAFTSSPIEL (
	ID INT(11) NOT NULL,
	MANNSCHAFT1_ID INT(11) NOT NULL,
	MANNSCHAFT2_ID INT(11) NOT NULL,
	PUNKTE_MANNSCHAFT1 INT(11) NOT NULL,
	PUNKTE_MANNSCHAFT2 INT(11) NOT NULL,
	TURNIER_ID INT(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle EINZELSPIEL
--
CREATE TABLE EINZELSPIEL (
	ID INT(11) NOT NULL,
	PERSON1_ID INT(11) NOT NULL,
	PERSON2_ID INT(11) NOT NULL,
	PUNKTE_PERSON1 INT(11) NOT NULL,
	PUNKTE_PERSON2 INT(11) NOT NULL,
	TURNIER_ID INT(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle MATERIALWART
--
CREATE TABLE MATERIALWART (
  ID int(11) NOT NULL,
  PERSON_ID int(11) NOT NULL,
  ANZAHL_BAELLE int(11) NOT NULL,
  ANZAHL_WASSERFLASCHEN int(11) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle BENUTZERROLLE
--
CREATE TABLE BENUTZERROLLE (
  ID int(11) NOT NULL,
  BEZEICHNUNG varchar(50) NOT NULL
);

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle BENUTZER
--
CREATE TABLE BENUTZER (
  ID int(11) NOT NULL,
  BENUTZERNAME varchar(50) NOT NULL,
  PASSWORT varchar(50) NOT NULL,
  ROLLE_ID INT(11) NOT NULL
);

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle MANNSCHAFT
--
ALTER TABLE MANNSCHAFT
  ADD PRIMARY KEY (ID),
  ADD KEY SPORTART_ID (SPORTART_ID);

--
-- Indizes für die Tabelle PERSON
--
ALTER TABLE PERSON
  ADD PRIMARY KEY (ID);

--
-- Indizes für die Tabelle FUSSBALLSPIELER
--
ALTER TABLE FUSSBALLSPIELER
  ADD PRIMARY KEY (ID),
  ADD KEY PERSON_ID (PERSON_ID);

--
-- Indizes für die Tabelle HANDBALLSPIELER
--
ALTER TABLE HANDBALLSPIELER
  ADD PRIMARY KEY (ID),
  ADD KEY PERSON_ID (PERSON_ID);

--
-- Indizes für die Tabelle TENNISSPIELER
--
ALTER TABLE TENNISSPIELER
  ADD PRIMARY KEY (ID),
  ADD KEY PERSON_ID (PERSON_ID);


--
-- Indizes für die Tabelle PHYSIO
--
ALTER TABLE PHYSIO
  ADD PRIMARY KEY (ID),
  ADD KEY PERSON_ID (PERSON_ID);

--
-- Indizes für die Tabelle TRAINER
--
ALTER TABLE TRAINER
  ADD PRIMARY KEY (ID),
  ADD KEY PERSON_ID (PERSON_ID);

--
-- Indizes für die Tabelle PERSONEN_MANNSCHAFTEN
--
ALTER TABLE PERSONEN_MANNSCHAFTEN
  ADD PRIMARY KEY (ID),
  ADD KEY PERSON_ID (PERSON_ID),
  ADD KEY MANNSCHAFT_ID (MANNSCHAFT_ID);

-- Indizes für die Tabelle SPORTART
--
ALTER TABLE SPORTART
  ADD PRIMARY KEY (ID);

-- Indizes für die Tabelle TURNIERART
--
ALTER TABLE TURNIERART
  ADD PRIMARY KEY (ID);

-- Indizes für die Tabelle TURNIER
--
ALTER TABLE TURNIER
  ADD PRIMARY KEY (ID),
  ADD KEY SPORTART_ID (SPORTART_ID),
  ADD KEY TURNIERART_ID (TURNIERART_ID);

-- Indizes für die Tabelle TURNIER_PERSON
--
ALTER TABLE TURNIER_PERSON
  ADD PRIMARY KEY (ID),
  ADD KEY PERSON_ID (PERSON_ID),
  ADD KEY TURNIER_ID (TURNIER_ID);

-- Indizes für die Tabelle TURNIER_MANNSCHAFT
--
ALTER TABLE TURNIER_MANNSCHAFT
  ADD PRIMARY KEY (ID),
  ADD KEY MANNSCHAFT_ID (MANNSCHAFT_ID),
  ADD KEY TURNIER_ID (TURNIER_ID);

-- Indizes für die Tabelle MANNSCHAFTSSPIEL
--
ALTER TABLE MANNSCHAFTSSPIEL
  ADD PRIMARY KEY (ID),
  ADD KEY MANNSCHAFT1_ID (MANNSCHAFT1_ID),
  ADD KEY MANNSCHAFT2_ID (MANNSCHAFT2_ID),
  ADD KEY TURNIER_ID (TURNIER_ID);

-- Indizes für die Tabelle EINZELSSPIEL
--
ALTER TABLE EINZELSPIEL
  ADD PRIMARY KEY (ID),
  ADD KEY PERSON1_ID (PERSON1_ID),
  ADD KEY PERSON2_ID (PERSON2_ID),
  ADD KEY TURNIER_ID (TURNIER_ID);	

--
-- Indizes für die Tabelle HANDBALLSPIELER
--
ALTER TABLE MATERIALWART
  ADD PRIMARY KEY (ID),
  ADD KEY PERSON_ID (PERSON_ID);

--
-- Indizes für die Tabelle BENUTZERROLLE
--
ALTER TABLE BENUTZERROLLE
  ADD PRIMARY KEY (ID);

-- Indizes für die Tabelle BENUTZER
--
ALTER TABLE BENUTZER
  ADD PRIMARY KEY (ID),
  ADD KEY ROLLE_ID (ROLLE_ID);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle MANNSCHAFT
--
ALTER TABLE MANNSCHAFT
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle PHYSIO
--
ALTER TABLE PHYSIO
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle PERSON
--
ALTER TABLE PERSON
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle TRAINER
--
ALTER TABLE TRAINER
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle SPORTART
--
ALTER TABLE SPORTART
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;
  
--
-- AUTO_INCREMENT für Tabelle PERSONEN_MANNSCHAFTEN
--
ALTER TABLE PERSONEN_MANNSCHAFTEN
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;
  
--
-- AUTO_INCREMENT für Tabelle FUSSBALLSPIELER
--
ALTER TABLE FUSSBALLSPIELER
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle HANDBALLSPIELER
--
ALTER TABLE HANDBALLSPIELER
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle TENNISSPIELER
--
ALTER TABLE TENNISSPIELER
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle TURNIERART
--
ALTER TABLE TURNIERART
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle TURNIER
--
ALTER TABLE TURNIER
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle TURNIER_PERSON
--
ALTER TABLE TURNIER_PERSON
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle TURNIER_MANNSCHAFT
--
ALTER TABLE TURNIER_MANNSCHAFT
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle MANNSCHAFTSSPIEL
--
ALTER TABLE MANNSCHAFTSSPIEL
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle EINZELSPIEL
--
ALTER TABLE EINZELSPIEL
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle MATERIALWART
--
ALTER TABLE MATERIALWART
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle BENUTZERROLLE
--
ALTER TABLE BENUTZERROLLE
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT für Tabelle BENUTZER
--
ALTER TABLE BENUTZER
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT;

--
-- Constraints der exportierten Tabellen
--

--
-- Constraints der Tabelle TRAINER
--
ALTER TABLE TRAINER
  ADD CONSTRAINT FK_TRAINER_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints der Tabelle FUSSBALLSPIELER
--
ALTER TABLE FUSSBALLSPIELER
  ADD CONSTRAINT FK_FUSSBALLSPIELER_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE;
   
--
-- Constraints der Tabelle HANDBALLSPIELER
--
ALTER TABLE HANDBALLSPIELER
  ADD CONSTRAINT FK_HANDBALLSPIELER_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE;   

--
-- Constraints der Tabelle TENNISSPIELER
--
ALTER TABLE HANDBALLSPIELER
  ADD CONSTRAINT FK_TENNISSPIELER_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE;   


--
-- Constraints der Tabelle PHYSIO
--
ALTER TABLE PHYSIO
  ADD CONSTRAINT FK_PHYSIO_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE;
      
--
-- Constraints der Tabelle MANNSCHAFT
--
ALTER TABLE MANNSCHAFT
  ADD CONSTRAINT FK_MANNSCHAFT_SPORTART_ID FOREIGN KEY (SPORTART_ID) REFERENCES SPORTART (ID) ON DELETE CASCADE ON UPDATE CASCADE;
        
--
-- Constraints der Tabelle PERSONEN_MANNSCHAFT
--
ALTER TABLE PERSONEN_MANNSCHAFTEN
  ADD CONSTRAINT FK_PERSONEN_MANNSCHAFTEN_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_PERSONEN_MANNSCHAFTEN_MANNSCHAFT_ID FOREIGN KEY (MANNSCHAFT_ID) REFERENCES MANNSCHAFT (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints der Tabelle TURNIER
--
ALTER TABLE TURNIER
  ADD CONSTRAINT FK_TURNIER_SPORTART_ID FOREIGN KEY (SPORTART_ID) REFERENCES SPORTART (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_TURNIER_TURNIERART_ID FOREIGN KEY (TURNIERART_ID) REFERENCES TURNIERART (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints der Tabelle TURNIER_PERSON
--
ALTER TABLE TURNIER_PERSON
  ADD CONSTRAINT FK_TURNIER_PERSON_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_TURNIER_PERSON_TURNIER_ID FOREIGN KEY (TURNIER_ID) REFERENCES TURNIER (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints der Tabelle TURNIER_MANNSCHAFT
--
ALTER TABLE TURNIER_MANNSCHAFT
  ADD CONSTRAINT FK_TURNIER_MANNSCHAFT_MANNSCHAFT_ID FOREIGN KEY (MANNSCHAFT_ID) REFERENCES MANNSCHAFT (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_TURNIER_MANNSCHAFT_TURNIER_ID FOREIGN KEY (TURNIER_ID) REFERENCES TURNIER (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints der Tabelle MANNSCHAFTSSPIEL
--
ALTER TABLE MANNSCHAFTSSPIEL
  ADD CONSTRAINT FK_MANNSCHAFTSSPIEL_MANNSCHAFT1_ID FOREIGN KEY (MANNSCHAFT1_ID) REFERENCES MANNSCHAFT (ID) ON DELETE CASCADE ON UPDATE CASCADE,  
  ADD CONSTRAINT FK_MANNSCHAFTSSPIEL_MANNSCHAFT2_ID FOREIGN KEY (MANNSCHAFT2_ID) REFERENCES MANNSCHAFT (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_MANNSCHAFTSSPIEL_TURNIER_ID FOREIGN KEY (TURNIER_ID) REFERENCES TURNIER (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints der Tabelle EINZELSPIEL
--
ALTER TABLE EINZELSPIEL
  ADD CONSTRAINT FK_EINZELSPIEL_PERSON1_ID FOREIGN KEY (PERSON1_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE,  
  ADD CONSTRAINT FK_EINZELSPIEL_PERSON2_ID FOREIGN KEY (PERSON2_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT FK_EINZELSPIEL_TURNIER_ID FOREIGN KEY (TURNIER_ID) REFERENCES TURNIER (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints der Tabelle MATERIALWART
--
ALTER TABLE MATERIALWART
  ADD CONSTRAINT FK_MATERIALWART_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints der Tabelle BENUTZER
--
ALTER TABLE BENUTZER
  ADD CONSTRAINT FK_BENUTZER_ROLLE FOREIGN KEY (ROLLE_ID) REFERENCES BENUTZERROLLE (ID) ON DELETE CASCADE ON UPDATE CASCADE;