-- DELIMITER ||
CREATE FUNCTION CheckPassword (BENUTZERNAME_b VARCHAR(50), PASSWORT_p VARCHAR(50))
    RETURNS BOOL
    NOT DETERMINISTIC
    READS SQL DATA
BEGIN
    RETURN EXISTS (SELECT ID FROM BENUTZER WHERE BENUTZERNAME = BENUTZERNAME_b AND PASSWORT = PASSWORT_p);
END;
-- ||
-- DELIMITER ;
-- SELECT CheckPassword('a','b');